puts 'The students of Directory Academy'
puts '____________'
puts 'Dr. Hannibal Lecter'
puts 'Darth Vader'
puts 'Nurse Ratched'
puts 'Michael Corleone'
puts 'Alex DeLarge'
puts 'The wicked Witch of the West'
puts 'Terminator'
puts 'Freddu Krueger'
puts 'The Joker'
puts 'Joffrey Baratheon'
puts 'Norman Bates'
print 'Overall, we have '
print 11
puts ' great students'

